// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('js/osml/base.js', ['osml', 'osml.FeatureCollector', 'osml.format'], [], false);
goog.addDependency('js/osml/featurepopup.js', ['osml.FeaturePopup'], ['osml.Popup', 'osml.preprocessors.Preprocessor', 'osml.widgets.Widget', 'osml.widgets.nl'], false);
goog.addDependency('js/osml/formatosmjson.js', ['osml.FormatOSMJSON'], ['ol.format.JSONFeature'], false);
goog.addDependency('js/osml/layerdef.js', ['osml.LayerDef'], ['osml'], false);
goog.addDependency('js/osml/layertree.js', ['osml.LayerTree', 'osml.LayerTreeNode'], ['osml.LayerDef', 'osml.Node', 'osml.Tree'], false);
goog.addDependency('js/osml/layertreecontrol.js', ['osml.LayerTreeControl'], ['ol.control.Control', 'osml', 'osml.LayerTree'], false);
goog.addDependency('js/osml/nominatim.js', ['osml.NominatimLayer', 'osml.NominatimSearchBox', 'osml.NominatimSource'], ['ol.layer.Vector', 'osml', 'osml.Query', 'osml.SearchBox', 'osml.format.OSMXML'], false);
goog.addDependency('js/osml/osmxmlformat.js', ['osml.format.OSMXML', 'osml.format.OSMXML.GeometryFactory'], ['goog.array', 'goog.asserts', 'goog.dom.NodeType', 'goog.object', 'ol.Feature', 'ol.format.Feature', 'ol.format.XMLFeature', 'ol.geom.GeometryLayout', 'ol.geom.LineString', 'ol.geom.Point', 'ol.geom.Polygon', 'ol.proj', 'ol.xml', 'osml.format'], false);
goog.addDependency('js/osml/overpass_source.js', ['osml.OverpassSource'], ['ol.format.OSMXML', 'ol.source.Vector', 'osml', 'osml.FormatOSMJSON', 'osml.ProgressControl', 'osml.Query'], false);
goog.addDependency('js/osml/overpasslayer.js', ['osml.OverpassLayer'], ['ol.layer.Vector', 'osml.OverpassSource'], false);
goog.addDependency('js/osml/popup.js', ['osml.Popup'], ['ol.Overlay', 'osml'], false);
goog.addDependency('js/osml/preprocessors.js', ['osml.preprocessors', 'osml.preprocessors.AmenityPreprocessor', 'osml.preprocessors.HideTagsPreprocessor', 'osml.preprocessors.NamePreprocessor', 'osml.preprocessors.Preprocessor', 'osml.preprocessors.TagPreprocessor', 'osml.preprocessors.TourismPreprocessor'], ['osml'], false);
goog.addDependency('js/osml/progresscontrol.js', ['osml.ProgressControl'], ['ol.control.Control', 'osml'], false);
goog.addDependency('js/osml/search.js', ['osml.Query', 'osml.SearchBox'], ['ol.control.Control'], false);
goog.addDependency('js/osml/site.js', ['osml.Site'], ['osml.FeaturePopup', 'osml.LayerDef', 'osml.LayerTreeControl', 'osml.OverpassLayer', 'osml.ProgressControl', 'osml.SearchBox'], false);
goog.addDependency('js/osml/tree.js', ['osml.Node', 'osml.Tree'], ['osml'], false);
goog.addDependency('js/osml/widgets.js', ['osml.widgets.Address', 'osml.widgets.BrowseOsm', 'osml.widgets.Directions', 'osml.widgets.EditJosm', 'osml.widgets.EditOnline', 'osml.widgets.Email', 'osml.widgets.Facebook', 'osml.widgets.Fax', 'osml.widgets.HtmlWidget', 'osml.widgets.Phone', 'osml.widgets.Tab', 'osml.widgets.TabPane', 'osml.widgets.Title', 'osml.widgets.Twitter', 'osml.widgets.ViewBing', 'osml.widgets.ViewGoogle', 'osml.widgets.ViewMapillary', 'osml.widgets.ViewMtM', 'osml.widgets.ViewOsm', 'osml.widgets.Widget', 'osml.widgets.WidgetGroup', 'osml.widgets.Wikipedia'], ['osml'], false);
goog.addDependency('js/osml/widgets.nl.js', ['osml.widgets.nl', 'osml.widgets.nl.Departures', 'osml.widgets.nl.ViewBagViewer', 'osml.widgets.nl.ViewDeHollandseMolen', 'osml.widgets.nl.ViewKvk', 'osml.widgets.nl.ViewMolendatabase', 'osml.widgets.nl.ViewOpenKvk'], ['osml.widgets.Widget'], false);
